const properties = [
    {
        id: 1,
        image: 'property1.jpg',
        address: '123 Main St',
        description: 'This charming home is located in a quiet neighborhood, offering a peaceful retreat with spacious rooms, a beautiful backyard, and modern appliances. Ideal for those seeking comfort and convenience.',
        price: '$500,000',
        rent: '$2,000/month',
        sqft: '2,000 sq. ft.',
        bedrooms: 3,
        bathrooms: 2,
        appliances: 'Refrigerator, Dishwasher, Microwave, Oven',
        basement: true,
        flooring: 'Hardwood',
        heating: 'Central Heating',
        cooling: 'Central Air Conditioning',
        lotSize: '0.25 acres',
        yearBuilt: 2000,
        hoa: false,
    },
    {
        id: 2,
        image: 'property2.jpg',
        address: '456 Elm St',
        description: 'Modern and spacious home with high-end finishes. Enjoy the large backyard, perfect for entertaining guests. Conveniently located near schools and parks. This property is a true gem, offering both luxury and comfort.',
        price: '$700,000',
        rent: '$2,500/month',
        sqft: '2,500 sq. ft.',
        bedrooms: 4,
        bathrooms: 3,
        appliances: 'Refrigerator, Oven, Washer, Dryer',
        basement: false,
        flooring: 'Carpet, Tile',
        heating: 'Radiant Heating',
        cooling: 'Split System Air Conditioning',
        lotSize: '0.3 acres',
        yearBuilt: 2010,
        hoa: true,
    },
    {
        id: 3,
        image: 'property3.jpg',
        address: '789 Oak Ave',
        description: 'Stunning contemporary home with panoramic views. This property features a gourmet kitchen, expansive living spaces, and a private outdoor oasis. Perfect for those who appreciate modern design and luxury living.',
        price: '$1,200,000',
        rent: '$3,500/month',
        sqft: '3,200 sq. ft.',
        bedrooms: 5,
        bathrooms: 4,
        appliances: 'Sub-Zero Refrigerator, Viking Range, Dishwasher',
        basement: true,
        flooring: 'Marble, Hardwood',
        heating: 'Underfloor Heating',
        cooling: 'Central Air Conditioning',
        lotSize: '0.5 acres',
        yearBuilt: 2015,
        hoa: false,
    },
    {
        id: 4,
        image: 'property4.jpg',
        address: '101 Pine Lane',
        description: 'Classic colonial-style home in a family-friendly neighborhood. This property offers a cozy atmosphere with a fireplace, spacious bedrooms, and a fenced backyard. Perfect for those who appreciate traditional charm.',
        price: '$450,000',
        rent: '$1,800/month',
        sqft: '1,800 sq. ft.',
        bedrooms: 4,
        bathrooms: 2.5,
        appliances: 'Dishwasher, Range, Washer, Dryer',
        basement: false,
        flooring: 'Hardwood, Carpet',
        heating: 'Forced Air',
        cooling: 'Window Units',
        lotSize: '0.2 acres',
        yearBuilt: 1995,
        hoa: true,
    },
    {
        id: 5,
        image: 'property5.jpg',
        address: '222 Maple Street',
        description: 'Quaint cottage-style home with a picturesque garden. This property offers a peaceful retreat with vintage charm, hardwood floors, and a sunlit kitchen. Perfect for those who seek a cozy and inviting home.',
        price: '$300,000',
        rent: '$1,200/month',
        sqft: '1,200 sq. ft.',
        bedrooms: 2,
        bathrooms: 1,
        appliances: 'Refrigerator, Oven',
        basement: false,
        flooring: 'Hardwood',
        heating: 'Baseboard Heating',
        cooling: 'None',
        lotSize: '0.15 acres',
        yearBuilt: 1940,
        hoa: false,
    },
    {
        id: 6,
        image: 'property6.jpg',
        address: '789 Oak Avenue',
        description: 'Modern and spacious family home with a beautiful backyard. This property features high-end finishes, an open-concept kitchen, and a master suite with a walk-in closet. Ideal for those who appreciate contemporary living.',
        price: '$600,000',
        rent: '$2,500/month',
        sqft: '2,800 sq. ft.',
        bedrooms: 4,
        bathrooms: 3.5,
        appliances: 'Refrigerator, Dishwasher, Microwave, Oven, Washer, Dryer',
        basement: true,
        flooring: 'Tile, Carpet',
        heating: 'Forced Air Heating',
        cooling: 'Central Air Conditioning',
        lotSize: '0.3 acres',
        yearBuilt: 2015,
        hoa: true,
    },
    {
        id: 7,
        image: 'property7.jpg',
        address: '456 Pine Lane',
        description: 'Charming colonial-style home in a friendly neighborhood. This property offers classic features, a spacious living room, and a backyard perfect for gatherings. A delightful home for those who appreciate traditional architecture.',
        price: '$400,000',
        rent: '$1,800/month',
        sqft: '1,500 sq. ft.',
        bedrooms: 3,
        bathrooms: 2,
        appliances: 'Refrigerator, Oven, Washer, Dryer',
        basement: true,
        flooring: 'Hardwood',
        heating: 'Radiant Heating',
        cooling: 'Window Air Conditioning',
        lotSize: '0.2 acres',
        yearBuilt: 1955,
        hoa: false,
    },
    {
        id: 8,
        image: 'property8.jpg',
        address: '987 Cedar Drive',
        description: 'Contemporary loft-style living in the heart of the city. This property boasts industrial features, an open floor plan, and skyline views. Perfect for urban dwellers seeking a stylish and convenient lifestyle.',
        price: '$800,000',
        rent: '$3,000/month',
        sqft: '1,800 sq. ft.',
        bedrooms: 2,
        bathrooms: 2,
        appliances: 'Refrigerator, Dishwasher, Microwave, Oven, Washer, Dryer',
        basement: false,
        flooring: 'Concrete',
        heating: 'Central Heating',
        cooling: 'Central Air Conditioning',
        lotSize: 'N/A',
        yearBuilt: 2010,
        hoa: true,
    },
    {
        id: 9,
        image: 'property9.jpg',
        address: '654 Birch Street',
        description: 'Elegant Victorian-style home with intricate details and a wrap-around porch. This property features a grand staircase, original hardwood floors, and a beautifully landscaped garden. A timeless residence for those who appreciate classic architecture.',
        price: '$750,000',
        rent: '$2,800/month',
        sqft: '2,400 sq. ft.',
        bedrooms: 4,
        bathrooms: 3,
        appliances: 'Refrigerator, Oven, Washer, Dryer',
        basement: true,
        flooring: 'Hardwood, Tile',
        heating: 'Radiant Heating',
        cooling: 'Window Air Conditioning',
        lotSize: '0.25 acres',
        yearBuilt: 1900,
        hoa: false,
    },
    {
        id: 10,
        image: 'property10.jpg',
        address: '333 Elm Avenue',
        description: 'Mediterranean-inspired villa with a private courtyard. This property offers a luxurious living space, high ceilings, and a gourmet kitchen. Ideal for those seeking a sophisticated and private oasis.',
        price: '$1,200,000',
        rent: '$4,500/month',
        sqft: '3,500 sq. ft.',
        bedrooms: 5,
        bathrooms: 4.5,
        appliances: 'Refrigerator, Dishwasher, Microwave, Oven, Washer, Dryer',
        basement: false,
        flooring: 'Tile, Hardwood',
        heating: 'Forced Air Heating',
        cooling: 'Central Air Conditioning',
        lotSize: '0.5 acres',
        yearBuilt: 2018,
        hoa: true,
    }





    // Add more properties as needed
];
